apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - loki/configmap.yaml
  - loki/statefulset.yaml
  - loki/service.yaml
  - promtail/rbac.yaml
  - promtail/configmap.yaml
  - promtail/daemonset.yaml

patches:
  - path: patches/grafana-loki-datasource.yaml
    target:
      kind: ConfigMap
      name: grafana-datasources
      namespace: monitoring
